Create Task Model, unit-tests and fixtures
oboldinsimaland/tasks-app pull request #4
Opened 2017-08-01 03:42 UTC by oboldinsimaland

2017-08-01 05:59 UTC, pastuhov requested changes

2017-08-01 05:59 UTC, pastuhov commented on common/fixtures/TaskFixture.php
> +}
?!

2017-08-01 05:59 UTC, pastuhov commented on common/models/Task.php
> +    const SCENARIO_INDEX = 'index';         // сценарий для вывода всех задач
сценарии тут не нужны

2017-08-01 05:59 UTC, pastuhov commented on common/models/Task.php
> +            [['begin_at', 'end_at', 'is_complete', 'description'], 'required', 'on' => self::SCENARIO_INDEX],
валидацию полей для поиска лучше сделать в поисковой модели (TaskSearch)

2017-08-01 05:59 UTC, pastuhov commented on common/models/Task.php
> +    public function fixtures()
что это?

2017-08-01 05:59 UTC, pastuhov commented on common/models/Task.php
> +class Task extends ActiveRecord
Phpdoc

2017-08-01 05:59 UTC, pastuhov commented on common/models/Task.php
> +    public function rules(){
phpdoc

2017-08-01 09:45 UTC, oboldinsimaland commented on common/fixtures/TaskFixture.php
> +}
fixed

2017-08-01 09:46 UTC, pastuhov requested changes

2017-08-01 09:46 UTC, pastuhov commented on .gitignore
> +/frontend/log.txt
1. опять нет пустой строки
2. не должно быть тут игноров логов
3. логи обычно лежат в /домен/runtime/logs

2017-08-01 09:50 UTC, pastuhov requested changes

2017-08-01 09:50 UTC, pastuhov commented on common/models/Task.php
> +
не должно быть пустых строк после phpdoc

2017-08-01 09:50 UTC, pastuhov commented on common/fixtures/TaskFixture.php
> +<?php
фикстуры и их данные должны лежать в tests

пример
https://github.com/yiisoft/yii2-app-advanced/tree/master/frontend/tests/_data

2017-08-02 05:39 UTC, pastuhov requested changes

2017-08-02 05:39 UTC, pastuhov commented on common/models/Task.php
> +     * Returns a user
говорили об этом

просто - User

2017-08-02 05:39 UTC, pastuhov commented on common/fixtures/data/task.php
> +<?php
не должно быть common/fixtures

2017-08-02 05:39 UTC, pastuhov commented on common/models/TaskSearch.php
> +        return [
мыссивы нужно размазать по строкам

2017-08-02 05:39 UTC, pastuhov commented on common/models/Task.php
> +            [['begin_at', 'end_at'], 'safe'],
такая валидация не пойдет, нужно проверить дату там

2017-08-02 11:24 UTC, pastuhov approved these changes

2017-08-02 11:34 UTC, merged