Create action
oboldinsimaland/tasks-app pull request #8
Opened 2017-08-04 09:46 UTC by oboldinsimaland

2017-08-04 10:27 UTC, pastuhov requested changes

2017-08-04 10:27 UTC, pastuhov commented on frontend/tests/functional/CreateTaskCest.php
> +        $I->see('Купить новый iPad');
надо проверить что она в базе появилась

2017-08-04 10:27 UTC, pastuhov commented on frontend/controllers/SiteController.php
> +            $task->begin_at = $model->begin_at;
вместо присваивания можно тоже load() сделать?

2017-08-04 10:27 UTC, pastuhov commented on common/models/CreateTaskForm.php
> +
куча пустых строк

2017-08-06 16:50 UTC, oboldinsimaland commented on common/models/CreateTaskForm.php
> +
fixed

2017-08-06 16:50 UTC, oboldinsimaland commented on frontend/controllers/SiteController.php
> +            $task->begin_at = $model->begin_at;
fixed

2017-08-06 16:50 UTC, oboldinsimaland commented on frontend/tests/functional/CreateTaskCest.php
> +        $I->see('Купить новый iPad');
fixed

2017-08-07 05:24 UTC, pastuhov requested changes

2017-08-07 05:24 UTC, pastuhov commented on common/models/CreateTaskForm.php
> +    public $begin_at;
phpdoc везде

2017-08-07 05:56 UTC, oboldinsimaland commented on common/models/CreateTaskForm.php
> +    public $begin_at;
fixed

2017-08-07 06:31 UTC, pastuhov approved these changes

2017-08-07 06:34 UTC, merged